stages:

  feature_engineering:

    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - data/raw/credit_card_fraud_10k.csv
    outs:
      - data/processed/credit_card_fraud_engineered.csv
  

  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - data/processed/credit_card_fraud_engineered.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - models/preprocess_scaler.pkl

  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/xgboost_model.pkl

